local lib = loadstring(game:HttpGet("https://raw.githubusercontent.com/mopsfl/rbxmopshub/main/lib.lua", true))()
local w = lib:Window({ gameName = "Test Game", title = "mopsHub" })
local tab1 = w:CreateTab({ tabtitle = "Test Tab 1" })
local tab2 = w:CreateTab({ tabtitle = "Test Tab 2" })
tab1:CreateLabel({LabelText="Label1"})
tab2:CreateLabel({LabelText="Label2"})
tab1:CreateButton({btnText="Test Button"}, function()
	print(game.Players.LocalPlayer.Name)
end)
tab2:CreateToggle({toggleText="Test Toggle"}, function(t)
	print(t)
end)
tab1:CreateSlider({max=250,min=16,s=16}, function(v)
	game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = v
	print(v)
end)
